import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, BadgeCheck, CircleDollarSign, Coins, ExternalLink, Flame, Info, LockKeyhole, PieChart, ShieldCheck, Sparkles, Users, Zap } from "lucide-react";
import { fromUnits } from "@/lib/format";
import { getLaunchCost } from "@/lib/near";

export const dynamic = "force-dynamic";

export default async function FeesPage() {
  const cost = await getLaunchCost(0, null, false).catch(() => null);
  return <main className="inner-page fees-page"><div className="inner-page-aura"/><div className="content-width fees-page-content">
    <div className="breadcrumbs"><Link href="/"><ArrowLeft size={14}/> Home</Link><span>/</span><strong>Fees & rewards</strong></div>
    <div className="fees-page-hero"><div><span className="eyebrow"><span className="tiny-line"/> OPEN ECONOMICS</span><h1>Every fee.<br/><span>Out in the open.</span></h1><p>No guesswork, no hidden cuts. Understand the cost of creating and trading a token on NEAR before you make your move.</p><Link href="/launch" className="button button-light">Launch your token <ArrowUpRight size={17}/></Link></div><div className="fees-hero-graphic"><div className="fees-hero-orbit orbit-a"/><div className="fees-hero-orbit orbit-b"/><div className="fees-hero-center"><span>POOL FEE</span><strong>1%</strong><small>RHEA DCL</small></div><span className="fees-hero-float float-a">70% CREATOR</span><span className="fees-hero-float float-b">0 PLATFORM LAUNCH FEE</span></div></div>

    <section className="fee-section"><div className="section-heading split-heading"><div><span className="eyebrow"><span className="tiny-line"/> 01 / TRADING</span><h2>Built to reward<br/>the ecosystem.</h2></div><div className="heading-side"><p>Every buy and sell in a Nearly launch pool pays a 1% Rhea DCL fee. Here is where that fee goes for new launches.</p></div></div><div className="fee-waterfall"><div className="fee-waterfall-head"><span>EXAMPLE: $1,000 TRADE</span><strong>$10.00 TOTAL POOL FEE</strong></div><div className="waterfall-track"><span className="waterfall-creator"/><span className="waterfall-protocol"/><span className="waterfall-referral"/><span className="waterfall-rhea"/></div><div className="waterfall-grid"><div><span className="waterfall-swatch creator"/><strong>Creator destination</strong><b>$5.60</b><small>56% of total fee</small></div><div><span className="waterfall-swatch protocol"/><strong>Protocol</strong><b>$1.60</b><small>16% of total fee</small></div><div><span className="waterfall-swatch referral"/><strong>Referral pot</strong><b>$0.80</b><small>8% of total fee</small></div><div><span className="waterfall-swatch rhea"/><strong>Rhea DEX</strong><b>$2.00</b><small>20% of total fee</small></div></div><div className="fee-explainer"><Info size={16}/><p>Rhea retains its DEX share first. The remaining LP fees collected by the Nearly factory split <strong>70% to the creator destination, 20% to protocol, and 10% to the referral pot</strong>. The example above shows the effective share of the entire 1% pool fee. Earlier tokens may have a different historical split.</p></div></div></section>

    <section className="fee-section"><div className="section-heading split-heading"><div><span className="eyebrow"><span className="tiny-line"/> 02 / LAUNCHING</span><h2>Create more.<br/>Pay only what&apos;s needed.</h2></div><div className="heading-side"><p>There is no additional GHOSTFUN or factory platform launch fee. Your deposit covers real onchain token and pool setup costs.</p></div></div><div className="launch-cost-grid"><div className="cost-feature-main"><span className="cost-feature-icon"><CircleDollarSign size={26}/></span><span>PLATFORM LAUNCH FEE</span><strong>0 <small>NEAR</small></strong><p>No extra listing charge. You only fund onchain storage, pool setup, your optional first buy, and NEAR gas.</p><Link href="/launch">See your exact launch quote <ArrowUpRight size={17}/></Link></div><div className="cost-detail-list"><div><span className="fee-detail-icon"><Coins size={19}/></span><span><b>Token account & storage</b><small>Contract account and token storage</small></span><strong>{cost ? `${fromUnits(cost.token_storage, 24, 4)} NEAR` : "Live quote"}</strong></div><div><span className="fee-detail-icon"><Zap size={19}/></span><span><b>Rhea pool creation</b><small>Your token&apos;s live trading market</small></span><strong>{cost ? `${fromUnits(cost.pool_create, 24, 4)} NEAR` : "Live quote"}</strong></div><div><span className="fee-detail-icon"><LockKeyhole size={19}/></span><span><b>Pool & position storage</b><small>Locked liquidity position setup</small></span><strong>{cost ? `${fromUnits(cost.dcl_storage, 24, 4)} NEAR` : "Live quote"}</strong></div><div className="cost-detail-total"><span>Typical base deposit without an image</span><strong>{cost ? `${fromUnits(cost.total, 24, 4)} NEAR` : "Calculated live"}</strong></div></div></div><p className="fee-under-note">The cost is queried directly from <code>quote_launch</code> on <code>nearlytrade.near</code> and can change with image size, tax configuration, and first buy. Gas is additional. The exact amount is shown before you approve a transaction.</p></section>

    <section className="fee-section"><div className="section-heading split-heading"><div><span className="eyebrow"><span className="tiny-line"/> 03 / YOUR CHOICE</span><h2>Set the terms.<br/>Build your community.</h2></div><div className="heading-side"><p>The protocol fee percentage is fixed, but what happens to your creator share and optional token tax is up to you at launch.</p></div></div><div className="fee-options-grid"><div><span className="fee-option-icon"><Coins size={23}/></span><h3>Fees to creator</h3><p>Receive your creator share from trading activity as your community grows.</p><span>CREATOR MODE <ArrowUpRight size={16}/></span></div><div><span className="fee-option-icon"><Users size={23}/></span><h3>Fees to holders</h3><p>Route the creator share to token holders according to their holdings.</p><span>HOLDERS MODE <ArrowUpRight size={16}/></span></div><div><span className="fee-option-icon"><Flame size={23}/></span><h3>Buyback & burn</h3><p>Use the share to buy back and burn tokens, reducing the supply.</p><span>BURN MODE <ArrowUpRight size={16}/></span></div></div><div className="tax-explainer"><div><span className="tax-icon"><PieChart size={23}/></span><h3>Optional custom token tax</h3><p>Set a buy and sell tax of 0–4% per side, then decide how the creator portion is shared between creator, buyback & burn, and holders. The protocol&apos;s share applies separately. These choices are fixed when the token launches.</p></div><div className="tax-badge">UP TO <strong>4%</strong><small>PER SIDE</small></div></div></section>

    <section className="fees-trust"><div className="fees-trust-icon"><ShieldCheck size={24}/></div><div><h3>Verify. Don&apos;t just trust.</h3><p>Contracts, pools and transactions live on NEAR. Check the factory source and onchain data yourself.</p></div><div className="fees-trust-links"><a href="https://github.com/sam3dsol/Nearlytrade" target="_blank" rel="noreferrer">Factory source <ExternalLink size={14}/></a><a href="https://nearblocks.io/address/nearlytrade.near" target="_blank" rel="noreferrer">View on NearBlocks <ExternalLink size={14}/></a></div></section>
    <div className="fees-page-cta"><span><Sparkles size={16}/> READY WHEN YOU ARE</span><h2>Your next big idea<br/>is one transaction away.</h2><Link href="/launch" className="button button-light">Create your token <ArrowRight size={17}/></Link></div>
  </div></main>;
}
