import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, BadgeCheck, Blocks, ChartNoAxesCombined, ChevronRight, CircleDollarSign, Coins, Flame, Globe2, LockKeyhole, MoveUpRight, Radio, Rocket, ShieldCheck, Sparkles, TrendingUp, Wallet, Zap } from "lucide-react";
import { MarketView } from "@/components/market-view";
import { compactNumber, usd } from "@/lib/format";
import { getMarkets, getStats } from "@/lib/near";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const [markets, stats] = await Promise.all([getMarkets("volume", 30), getStats()]);

  return <main>
    <section className="home-hero" aria-label="GHOSTFUN on NEAR">
      <div className="hero-video-wrap"><video className="hero-video" autoPlay loop muted playsInline preload="metadata"><source src="/media/hero.mp4" type="video/mp4" /></video><div className="hero-video-overlay" /></div>
      <div className="hero-content">
        <div className="hero-eyebrow"><span className="hero-eyebrow-dot" /> The next era of <span className="near-wordmark"><img src="/logos/near.png" alt="NEAR Protocol logo" width={16} height={16} />NEAR</span> starts here <ChevronRight size={14} /></div>
        <h1>The Next Generation<br />of <span>Onchain Trading</span></h1>
        <p>Discover what&apos;s next. Trade what you believe in. Launch your own token on NEAR — all in one powerful, open ecosystem.</p>
        <div className="hero-buttons"><Link className="button button-glass" href="/markets">Explore Markets <ArrowUpRight size={16} /></Link><Link className="button button-light" href="/launch">Start Building <ArrowUpRight size={16} /></Link></div>
        <div className="hero-microcopy"><span className="live-dot" /> LIVE ON NEAR MAINNET <span className="hero-micro-divider" /> NON-CUSTODIAL BY DESIGN</div>
      </div>
      <a href="#ecosystem" className="hero-scroll" aria-label="Scroll to explore"><span>SCROLL TO EXPLORE</span><ArrowDown size={16} /></a>
    </section>

    <section className="stats-section"><div className="content-width stats-grid">
      <div className="stat-card stat-card-special"><span className="stat-icon"><Blocks size={21} /></span><div className="stat-bottom"><strong>{stats ? `${compactNumber(stats.launches)}+` : "—"}</strong><span>Tokens launched</span></div><span className="stat-card-light" /></div>
      <div className="stat-card"><span className="stat-icon"><ChartNoAxesCombined size={21} /></span><div className="stat-bottom"><strong>{stats ? `${usd(stats.volumeUsd, true)}+` : "—"}</strong><span>Trading volume</span></div></div>
      <div className="stat-card"><span className="stat-icon"><Zap size={21} /></span><div className="stat-bottom"><strong>{stats ? `${compactNumber(stats.trades)}+` : "—"}</strong><span>Onchain trades</span></div></div>
      <div className="stat-card"><span className="stat-icon"><CircleDollarSign size={21} /></span><div className="stat-bottom"><strong>0 <small>NEAR</small></strong><span>Platform launch fee</span></div></div>
    </div></section>

    <section id="ecosystem" className="ecosystem-section section-spacing"><div className="content-width">
      <div className="section-heading centered"><span className="eyebrow"><span className="tiny-line" /> THE GHOSTFUN ECOSYSTEM</span><h2>One network. Endless<br />possibilities.</h2><p>Everything you need to discover, trade and create on NEAR, seamlessly connected in one place.</p></div>
      <div className="ecosystem-cards">
        <Link href="/markets" className="ecosystem-card ecosystem-trade"><div className="ecosystem-card-art trade-art"><span className="chart-art-grid" /><svg viewBox="0 0 640 280" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="tradeStroke" x1="0" y1="1" x2="1" y2="0"><stop stopColor="#395869"/><stop offset=".52" stopColor="#91a9bd"/><stop offset="1" stopColor="#e7f3ff"/></linearGradient><linearGradient id="tradeFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#d6ecff" stopOpacity=".2"/><stop offset="1" stopColor="#d6ecff" stopOpacity="0"/></linearGradient></defs><path d="M0 245 L70 215 L112 226 L156 168 L215 186 L261 147 L310 170 L352 121 L402 143 L455 76 L512 97 L559 40 L640 15 L640 280 L0 280Z" fill="url(#tradeFill)"/><path d="M0 245 L70 215 L112 226 L156 168 L215 186 L261 147 L310 170 L352 121 L402 143 L455 76 L512 97 L559 40 L640 15" stroke="url(#tradeStroke)" strokeWidth="3" fill="none"/></svg><div className="floating-price"><span>NEAR MARKET</span><b>+24.8%</b><TrendingUp size={16}/></div></div><div className="ecosystem-card-content"><span>01 / DISCOVER & TRADE</span><h3>Trade the moment.</h3><p>Explore live markets and trade emerging NEAR tokens directly from your own wallet.</p><span className="round-arrow"><ArrowUpRight size={20} /></span></div></Link>
        <Link href="/launch" className="ecosystem-card ecosystem-launch"><div className="ecosystem-card-art launch-art"><span className="launch-orbit orbit-one"/><span className="launch-orbit orbit-two"/><span className="launch-orbit orbit-three"/><span className="launch-core"><img src="/logos/near.png" alt="NEAR Protocol" width={130} height={130} /></span><span className="launch-satellite sat-rhea"><img src="/logos/rhea.png" alt="Rhea Finance" width={48} height={48} /><i>RHEA</i></span><span className="launch-satellite sat-nearly"><img src="/logos/nearly.webp" alt="Nearly launchpad" width={42} height={42} /><i>NEARLY</i></span><span className="launch-float float-one">✦</span><span className="launch-float float-two">✧</span></div><div className="ecosystem-card-content"><span>02 / CREATE & LAUNCH</span><h3>Build your universe.</h3><p>Launch a token in one transaction with a real Rhea pool and permanently locked liquidity.</p><span className="round-arrow"><ArrowUpRight size={20} /></span></div></Link>
      </div>
    </div></section>

    <section className="ecosystem-marquee"><div className="content-width"><span>BUILT FOR THE NEAR ECOSYSTEM</span><div className="ecosystem-logos">
        <b className="partner"><img src="/logos/near.png" alt="NEAR Protocol logo" width={28} height={28} /><span>NEAR</span></b>
        <b className="partner"><img src="/logos/rhea.png" alt="Rhea Finance logo" width={28} height={28} /><span>RHEA</span></b>
        <b className="partner"><img src="/logos/nearly.webp" alt="Nearly logo" width={28} height={28} /><span>NEARLY</span></b>
        <b className="partner"><img src="/logos/near.png" alt="NEAR Protocol logo" width={28} height={28} /><span>NEAR INTENTS</span></b>
      </div></div></section>

    <section id="markets" className="markets-section section-spacing"><div className="content-width"><div className="section-heading split-heading"><div><span className="eyebrow"><span className="tiny-line" /> THE MARKETPLACE</span><h2>The market is<br />yours to explore.</h2></div><div className="heading-side"><p>From the next breakout to the next big idea, see what is moving on NEAR in real time.</p><Link href="/markets" className="inline-link">Discover all markets <ArrowUpRight size={17} /></Link></div></div><MarketView initialMarkets={markets} stats={stats} /></div></section>

    <section id="about" className="why-section section-spacing"><div className="why-background"><span className="why-radial"/><span className="why-rings"/></div><div className="content-width why-inner"><span className="eyebrow"><span className="tiny-line" /> WHY GHOSTFUN?</span><h2>Designed for a more<br />open kind of finance.</h2><p>Powerful onchain infrastructure. An experience that feels effortless. This is trading, reimagined for everyone.</p><div className="why-grid"><div><span className="why-icon"><LockKeyhole size={19} /></span><strong>Non-custodial, always</strong><small>Your keys, your assets. Every transaction is signed by your wallet.</small></div><div><span className="why-icon"><Zap size={19} /></span><strong>Markets from block one</strong><small>New tokens are tradable on Rhea as soon as they go live.</small></div><div><span className="why-icon"><ShieldCheck size={19} /></span><strong>Liquidity locked</strong><small>Launch liquidity lives in an immutable, onchain locker.</small></div><div><span className="why-icon"><BadgeCheck size={19} /></span><strong>Transparent by design</strong><small>See the fees, slippage and minimum received before you sign.</small></div><div><span className="why-icon"><Globe2 size={19} /></span><strong>Open to everyone</strong><small>One global network, with no gatekeepers in the way.</small></div><div><span className="why-icon"><Coins size={19} /></span><strong>Creator-first rewards</strong><small>Choose where your share goes: to you, holders or buybacks.</small></div></div><Link href="/launch" className="button button-light why-button">Launch your token <ArrowUpRight size={16} /></Link></div></section>

    <section id="how-it-works" className="how-section section-spacing"><div className="content-width"><div className="section-heading centered"><span className="eyebrow"><span className="tiny-line" /> SIMPLE BY DESIGN</span><h2>Your next move starts here.</h2><p>From first idea to first trade, the path is yours to make.</p></div><div className="how-grid"><div className="how-card"><span className="step-number">01</span><span className="step-icon"><Wallet size={25} /></span><h3>Connect your wallet</h3><p>Bring the NEAR wallet you already trust. Nothing moves until you approve it.</p><span className="how-connector" /></div><div className="how-card"><span className="step-number">02</span><span className="step-icon"><Sparkles size={25} /></span><h3>Find your moment</h3><p>Explore live tokens or launch your own with customizable fee destinations.</p><span className="how-connector" /></div><div className="how-card"><span className="step-number">03</span><span className="step-icon"><MoveUpRight size={25} /></span><h3>Trade onchain</h3><p>Preview your quote, choose slippage, and sign securely on NEAR.</p></div></div></div></section>

    <section className="fees-home-section"><div className="content-width fees-home-inner"><div className="fees-home-copy"><span className="eyebrow"><span className="tiny-line" /> FEES, WITHOUT THE FINE PRINT</span><h2>More transparent.<br />More yours.</h2><p>Every launch uses a 1% Rhea pool. Creator fee share is split transparently, and launching costs only onchain storage and network gas — no added platform launch fee.</p><Link href="/fees" className="button button-glass">Explore fee breakdown <ArrowUpRight size={16} /></Link></div><div className="fee-visual"><div className="fee-visual-head"><span>POOL FEE DISTRIBUTION</span><Radio size={18} /></div><div className="fee-big-number">70<span>%</span></div><span className="fee-big-label">Creator share of LP fees</span><div className="fee-bar"><span/><span/><span/></div><div className="fee-labels"><span><i/> Creator 70%</span><span><i/> Protocol 20%</span><span><i/> Referral 10%</span></div><small>Factory split for newly launched tokens. Rhea&apos;s DEX share is separate.</small></div></div></section>

    <section className="faq-section section-spacing"><div className="content-width faq-layout"><div className="faq-intro"><span className="eyebrow"><span className="tiny-line" /> GOOD TO KNOW</span><h2>Questions?<br />Meet answers.</h2><p>Everything you need to know before your next move on NEAR.</p><Link href="/fees" className="inline-link">See all fee details <ArrowUpRight size={16} /></Link></div><div className="faq-list">
      <details><summary><span>01</span> What is GHOSTFUN? <span className="faq-plus">+</span></summary><p>GHOSTFUN is a non-custodial interface for discovering, trading and launching tokens on NEAR. Markets and launches are powered by the Nearly factory and Rhea liquidity pools.</p></details>
      <details><summary><span>02</span> How much does it cost to launch a coin? <span className="faq-plus">+</span></summary><p>There is no additional platform launch fee. The NEAR factory charges the onchain storage and pool creation deposit shown as a live quote before you sign. Network gas is additional.</p></details>
      <details><summary><span>03</span> Where do trading fees go? <span className="faq-plus">+</span></summary><p>Every trade pays a 1% Rhea pool fee. For newly launched coins, the factory distributes its collected LP fees 70% to the chosen creator destination, 20% to protocol, and 10% to the referral pot. Rhea retains its own DEX share.</p></details>
      <details><summary><span>04</span> Is the liquidity really locked? <span className="faq-plus">+</span></summary><p>Yes. The entire fixed 1 billion supply launches into a Rhea pool owned by a locker with no access keys and no liquidity withdrawal function. You can verify it onchain.</p></details>
      <details><summary><span>05</span> Do you ever hold my funds? <span className="faq-plus">+</span></summary><p>No. You connect your own NEAR wallet and approve each launch or swap yourself. GHOSTFUN never asks for your private keys.</p></details>
    </div></div></section>

    <section className="final-cta"><div className="final-cta-glow"/><div className="content-width final-cta-inner"><span className="eyebrow">THE FUTURE IS ONCHAIN</span><h2>What will you create<br />next?</h2><p>Join the next generation of builders and traders on NEAR.</p><div className="hero-buttons"><Link href="/markets" className="button button-glass">Explore Markets <ArrowUpRight size={16} /></Link><Link href="/launch" className="button button-light">Launch a Coin <ArrowUpRight size={16} /></Link></div><span className="cta-decoration"><Flame size={18} /> MADE FOR WHAT&apos;S NEXT</span></div></section>
  </main>;
}
